### ISSUE TITLE
Single line understanding - learning - not a problem with library

### ISSUE THREAD

**Issue by svdrummer** [highno/rtcvars#4]
Not an issue. Help request.
I have tried google, I just wanted to know what this line is doing, please

program_step = (program_step == 7) ? 1 : program_step + 1;

Program_step++  incremented if program_step == 7 ?

**Comment by highno** [comment]
No problem. 

(Term) ? TrueVal : FalseVal 

is an expression helper to selectively differ two expressions depending on a third expression. 

In short: if Term evaluates to true, then the expression returns TrueVal, else FalseVal.

In my case the whole line increments the variable unless 7 is reached. Instead of incrementing again it resets to 1. often this task is done by an increment/modulo-division line but that would reset the counter to 0 instead of 1. it also saves a division instruction.

**Comment by svdrummer** [comment]
Thank you !

I would have done it this way..before..

if (program_step < 8) {
        program_step++
    }
    else {
        program_step = 1
    }

**Comment by highno** [comment]
Yes. Often these constructs get rather messy with if/else clauses. 

I guess this is the "syntactic sugar" everyone talks about. If not, we'll it's sweet anyway :-)
